app/config/routes.rb
require 'authz/app_developer_constraint'

Rails.application.routes.draw do
  if Configuration.can_access_projects?
    get 'projects/import' => 'projects#import', :as => 'project_import'
    post 'projects/import' => 'projects#import_save', :as => 'project_import_save'

    resources :projects do
      root 'projects#index'
      get '/jobs/:cluster/:jobid' => 'projects#job_details', :defaults => { :format => 'turbo_stream' }, :as => 'job_details'
      delete '/jobs/:cluster/:jobid' => 'projects#delete_job', :as => 'delete_job'
      post '/jobs/:cluster/:jobid/stop' => 'projects#stop_job', :as => 'stop_job'

      resources :launchers do
        post 'submit', on: :member
        post 'save', on: :member
      end
    end
  end

  if Configuration.can_access_files?
    constraints(->(request) { request.params[:fs].to_s.match?(%r{^(?!(edit|api))[^/]+$}) }) do
      get 'files/:fs(/*filepath)' => 'files#fs', :defaults => { :fs => 'fs', :format => 'html' }, :format => false,
          :as => :files
      put 'files/:fs/*filepath' => 'files#update', :format => false, :defaults => { :fs => 'fs', :format => 'json' }

      get 'files/api/v1/:fs(/*filepath)' => 'files#fs', :defaults => { :fs => 'fs', :format => 'html' },
          :format => false
      put 'files/api/v1/:fs/*filepath' => 'files#update', :format => false,
          :defaults => { :fs => 'fs', :format => 'json' }
    end
    post 'files/upload/:fs' => 'files#upload', :defaults => { :fs => 'fs' } if Configuration.upload_enabled?

    get 'files', to: redirect("files/fs#{Dir.home}")
    get 'files/fs', to: redirect("files/fs#{Dir.home}")
    get 'frames/directory_frame' => 'files#directory_frame', as: 'directory_frame'
    
    resources :transfers, only: [:show, :create, :destroy]
  end

  if Configuration.can_access_file_editor?
    get 'files/edit/:fs/*filepath' => 'files#edit', :defaults => { :fs => 'fs', :path => '/', :format => 'html' },
        :format => false
    get 'files/edit/:fs' => 'files#edit', :defaults => { :fs => 'fs', :path => '/', :format => 'html' },
        :format => false
  end

  namespace :batch_connect do
    resources :sessions, only: [:index, :destroy]
    post 'sessions/:id/cancel', to: 'sessions#cancel', as: 'cancel_session'
    scope '*token', constraints: { token: %r{((usr/[^/]+)|dev|sys)/[^/]+(/[^/]+)?} } do
      resources :settings, only: [:show, :destroy]
      resources :session_contexts, only: [:new, :create]
      get "session_contexts/edit_settings/:id", to: "session_contexts#edit_settings", as: 'edit_settings'
      post "session_contexts/save_settings", to: "session_contexts#save_settings", as: 'save_settings'

      root 'session_contexts#new'
    end
  end
  get 'errors/not_found'
  get 'errors/internal_server_error'
  get 'dashboard/index'
  get 'logout' => 'dashboard#logout'

  get 'analytics/:type' => proc { [204, {}, ['']] }, :as => 'analytics'

  get 'apps/show/:name(/:type(/:owner))' => 'apps#show', :as => 'app', :defaults => { type: 'sys' }, :constraints => { owner: %r{[^/]+} }
  get 'apps/icon/:name(/:type(/:owner))' => 'apps#icon', :as => 'app_icon', :defaults => { type: 'sys' }, :constraints => { owner: %r{[^/]+} }
  get 'apps/index' => 'apps#index'

  get 'apps/restart' => 'apps#restart' if Configuration.app_sharing_enabled?

  root 'dashboard#index'

  scope 'admin/:type', constraints: Authz::AppDeveloperConstraint do
    resources :products, except: :destroy, param: :name, constraints: { type: /dev|usr/ } do
      nested do
        scope ':context' do
          resources :permissions, only: [:index, :new, :create, :destroy], param: :name
        end
      end
      member do
        patch 'cli/:cmd', to: 'products#cli', as: 'cli'
      end
      collection do
        get 'create_key'
        get 'new_from_git_remote'
        post 'create_from_git_remote'
      end
    end
  end

  if Configuration.can_access_activejobs?
    get '/activejobs' => 'active_jobs#index'
    get '/activejobs/json' => 'active_jobs#json', :defaults => { :format => 'json' }
    delete '/activejobs' => 'active_jobs#delete_job', :as => 'delete_job'
  end

  get '/system-status', to: 'system_status#index', as: 'system_status' if Configuration.can_access_system_status?

  post 'settings', :to => 'settings#update'

  if Configuration.widget_partials_enabled?
    match '/widgets/*widget_path', to: 'widgets#show', via: [:get, :post], as: 'widgets'
  end

  if Configuration.support_ticket_enabled?
    get '/support', to: 'support_ticket#new'
    post '/support', to: 'support_ticket#create'
  end

  get '/custom/:page_code', to: 'custom_pages#index', as: :custom_pages

  match '/404', :to => 'errors#not_found', :via => :all
  match '/500', :to => 'errors#internal_server_error', :via => :all

  get 'module_browser' => 'module_browser#index', :as => 'module_browser'

end

app/app/views/layouts/_announcements.html.erb
<% @announcements.select(&:valid?).reject(&:completed?).each do |announcement| %>
  <div id="announcement-<%=announcement.id%>" class="alert alert-<%= announcement.type %> announcement" role="alert">
    <div class="announcement-body"><%= raw OodAppkit.markdown.render(announcement.msg) %></div>
    <% if announcement.dismissible? %>
      <div class="d-grid gap-2 d-md-flex justify-content-md-end">
        <%=
          button_to(
            settings_path,
            method: :post,
            form_class: 'announcement-form',
            class: "btn btn-#{announcement.type} me-md-2 announcement-button",
            params: { settings: { announcements: { announcement.id => Time.now.localtime.strftime('%Y-%m-%d %H:%M:%S') } } }
          ) do
            announcement.button_text
          end
        %>
      </div>
    <% end %>
  </div>
<% end %>

app/app/views/layouts/_browser_warning.html.erb
<% if !browser.modern? %>
    <div class="alert alert-danger alert-dismissible" role="alert">
      <button type="button" class="btn-close" data-bs-dismiss="alert">
        <span class="sr-only">Close</span>
      </button>
      OnDemand requires a newer version of the browser you are using.
      Current browser requirements include IE Edge, Firefox 19+, Chrome 34+, Safari 8+.
    </div>
<% end %>

app/app/views/layouts/_config.html.erb
<!-- configuration options exposed to javascript -->
<div hidden id="ood_config"
  data-max-file-size="<%= Configuration.file_upload_max %>"
  data-download-enabled="<%= Configuration.download_enabled? %>"
  data-transfers-path="<%= transfers_path(format: "json") if respond_to?(:transfers_path) %>"
  data-root-path="<%= root_path %>"
  data-uppy-locale="<%= I18n.t('dashboard.uppy', :default => {}).to_json %>"
  data-bc-dynamic-js="<%= Configuration.bc_dynamic_js? %>"
  data-xdmod-url="<%= Configuration.xdmod_host %>"
  data-base-analytics-path="<%= analytics_path('delme').gsub(/[\/]*delme[\/]*/,'') %>"
  data-bc-poll-delay="<%= Configuration.bc_sessions_poll_delay %>"
  data-bc-index-url="<%= batch_connect_sessions_path %>"
  data-status-poll-delay="<%= Configuration.status_poll_delay %>"
  data-status-index-url="<%= system_status_path if respond_to?(:system_status_path) %>"
  data-support-path="<%= support_path if respond_to?(:support_path) %>"
  data-apps-datatable-page-length="<%= @user_configuration.apps_datatable[:page_length] %>"
></div>

app/app/views/layouts/_footer.html.erb
<footer class="d-flex m-0 mt-4 justify-content-between align-items-center p-4">
  <div class="me-2">
    <%= link_to "https://openondemand.org" do %>
      <%=
        image_tag(
          "OpenOnDemand_powered_by_RGB.svg",
          class: "footer-logo",
          alt: "Powered by Open OnDemand",
          height: "40px",
        )
      %>
    <% end %>
  </div>
  <span id="ood_version">OnDemand version: <%= Configuration.ood_version %></span>
</footer>

app/app/views/layouts/_google_analytics.html.erb
<%- tag_id = Configuration.google_analytics_tag_id -%>

<%- unless tag_id.nil? -%>
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=<%= tag_id %>"></script>
<script nonce="<%= content_security_policy_nonce %>">
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', '<%= tag_id %>');
</script>
<%- end -%>

app/app/views/layouts/active_jobs.html.erb
<%= render template: "layouts/application", locals: { layout_container_class: 'container-fluid' } %>

app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="<%= Configuration.locale %>">
<head>
  <style>
    .welcome-banner {
      background-color: #e6f0ff;
      color: #003366;
      font-size: 18px;
      padding: 10px;
      border: 1px solid #b3d1ff;
      margin-bottom: 15px;
    }
  </style>
  <title><%= content_for?(:title) ? yield(:title) : "Dashboard - #{@user_configuration.dashboard_title}" %></title>
  <%= favicon %>
  <%= javascript_include_tag 'application', nonce: true %>
  <% custom_javascript_paths.each do |custom_file_config| %>
    <script src="<%= custom_file_config[:src] %>" type="<%= custom_file_config[:type] %>" nonce="<%= content_security_policy_nonce %>"></script>
  <% end %>
  <%= stylesheet_link_tag 'application', nonce: content_security_policy_nonce, media: 'all', rel: 'preload stylesheet', as: 'style', type: 'text/css' %>
  <%= render partial: '/layouts/nav/styles', locals: { bg_color: @user_configuration.brand_bg_color, link_active_color: @user_configuration.brand_link_active_bg_color } %>
  <% custom_css_paths.each do |path| %>
    <link rel="stylesheet" media="all" href="<%= path %>" nonce="<%= content_security_policy_nonce %>" />
  <% end %>
  <%= render partial: 'layouts/google_analytics' %>
  <%= yield :head %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="profile" content="<%= @user_configuration.profile %>">
  <meta name="generator" content="Open OnDemand" />
  <%= render partial: 'layouts/config' %>
</head>
<body>
  <div class="welcome-banner">
    👋 Welcome to the Open OnDemand Portal built by Vedant Modi!
  </div>

  <header>
    <span class="row">
      <a href="#main_container" class="skip-link"><%= t('dashboard.skip_navigation') %></a>
    </span>
    <nav class="navbar navbar-expand-md shadow-sm navbar-color navbar-<%= @user_configuration.navbar_type %>">
      <ul class="navbar-nav w-100 align-items-center" role="menubar">
        <%= render partial: 'layouts/nav/logo' %>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbar">
          <% if @nav_bar.empty? %>
            <%= render partial: 'layouts/nav/featured_apps' %>
            <%= render partial: 'layouts/nav/group', collection: @nav_groups %>
            <%= render partial: 'layouts/nav/sessions', nav_groups: @nav_groups if Configuration.app_development_enabled? || @nav_groups.any?(&:has_batch_connect_apps?) %>
            <%= render partial: 'layouts/nav/all_apps' if @user_configuration.show_all_apps_link %>
          <% else %>
            <%= render partial: 'layouts/nav/custom_navigation', locals: { navigation: @nav_bar } %>
            <li class="nav-item">
              <a class="nav-link" href="/login">Login</a>
            </li>
          <% end %>
          <div class="ms-auto"></div>
          <% if @help_bar.empty? %>
            <%= render partial: 'layouts/nav/develop_dropdown' %>
            <%= render partial: 'layouts/nav/help_dropdown' %>
            <%= render partial: 'layouts/nav/user' %>
            <%= render partial: 'layouts/nav/log_out' %>
          <% else %>
            <%= render partial: 'layouts/nav/custom_navigation', locals: { navigation: @help_bar, menu_alignment: 'dropdown-menu-end' } %>
          <% end %>
        </div>
      </ul>
    </nav>
  </header>

  <div id="full_page_spinner" class="global-full-page-spinner d-none">
    <div class="spinner-border" role="status"></div>
  </div>

  <div id="main_container" class="<%= local_assigns[:layout_container_class] || 'container-md' %> content mt-4" role="main">
    <%= render "layouts/announcements" %>
    <%= render "layouts/browser_warning" %>

    <% if @my_quotas && @my_quotas.any? %>
      <%= render partial: "shared/insufficient_quota", locals: { quotas: @my_quotas } %>
    <% end %>

    <% if @my_balances && @my_balances.any? %>
      <%= render partial: "shared/insufficient_balance", locals: { balances: @my_balances } %>
    <% end %>

    <% if invalid_clusters.any? %>
      <%= render partial: "shared/bad_cluster_config" %>
    <% end %>

    <div id="js-alert-danger-template" class="d-none" aria-hidden="true">
      <div class="alert alert-danger alert-dismissible" role="alert">
        <button type="button" class="btn-close" data-bs-dismiss="alert">
          <span class="sr-only">Close</span>
        </button>
        ALERT_MSG
      </div>
    </div>

    <% if alert %>
      <div class="alert alert-danger alert-dismissible" role="alert">
        <button type="button" class="btn-close" data-bs-dismiss="alert">
          <span class="sr-only">Close</span>
        </button>
        <%= alert %>
      </div>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>

app/app/views/layouts/editor.html.erb
<%
content_for :head do
  javascript_include_tag 'editor', nonce: true
end

content_for :title do
  "File Editor - #{@user_configuration.dashboard_title}" + (@path.nil? ? "" : " - #{@path.basename.to_s}")
end
%>

<%= render template: "layouts/application", locals: { layout_container_class: 'container-fluid d-flex flex-column' } %>

app/app/views/layouts/files.html.erb
<%- unless turbo_frame_request? %>

  <%
  content_for :head do
    javascript_include_tag('files/index', nonce: true, type: 'module')
  end
  %>

  <%= render template: "layouts/application", locals: { layout_container_class: 'container-fluid' } %>
<%- end -%>

app/app/views/layouts/projects.html.erb
<%= render template: "layouts/application", locals: { layout_container_class: 'container-fluid' } %>