app/config/routes.rb
require 'authz/app_developer_constraint'

Rails.application.routes.draw do
  if Configuration.can_access_projects?
    get 'projects/import' => 'projects#import', :as => 'project_import'
    post 'projects/import' => 'projects#import_save', :as => 'project_import_save'

    resources :projects do
      root 'projects#index'
      get '/jobs/:cluster/:jobid' => 'projects#job_details', :defaults => { :format => 'turbo_stream' }, :as => 'job_details'
      delete '/jobs/:cluster/:jobid' => 'projects#delete_job', :as => 'delete_job'
      post '/jobs/:cluster/:jobid/stop' => 'projects#stop_job', :as => 'stop_job'

      resources :launchers do
        post 'submit', on: :member
        post 'save', on: :member
      end
    end
  end

  if Configuration.can_access_files?
    constraints(->(request) { request.params[:fs].to_s.match?(%r{^(?!(edit|api))[^/]+$}) }) do
      get 'files/:fs(/*filepath)' => 'files#fs', :defaults => { :fs => 'fs', :format => 'html' }, :format => false,
          :as => :files
      put 'files/:fs/*filepath' => 'files#update', :format => false, :defaults => { :fs => 'fs', :format => 'json' }

      get 'files/api/v1/:fs(/*filepath)' => 'files#fs', :defaults => { :fs => 'fs', :format => 'html' },
          :format => false
      put 'files/api/v1/:fs/*filepath' => 'files#update', :format => false,
          :defaults => { :fs => 'fs', :format => 'json' }
    end
    post 'files/upload/:fs' => 'files#upload', :defaults => { :fs => 'fs' } if Configuration.upload_enabled?

    get 'files', to: redirect("files/fs#{Dir.home}")
    get 'files/fs', to: redirect("files/fs#{Dir.home}")
    get 'frames/directory_frame' => 'files#directory_frame', as: 'directory_frame'
    
    resources :transfers, only: [:show, :create, :destroy]
  end

  if Configuration.can_access_file_editor?
    get 'files/edit/:fs/*filepath' => 'files#edit', :defaults => { :fs => 'fs', :path => '/', :format => 'html' },
        :format => false
    get 'files/edit/:fs' => 'files#edit', :defaults => { :fs => 'fs', :path => '/', :format => 'html' },
        :format => false
  end

  namespace :batch_connect do
    resources :sessions, only: [:index, :destroy]
    post 'sessions/:id/cancel', to: 'sessions#cancel', as: 'cancel_session'
    scope '*token', constraints: { token: %r{((usr/[^/]+)|dev|sys)/[^/]+(/[^/]+)?} } do
      resources :settings, only: [:show, :destroy]
      resources :session_contexts, only: [:new, :create]
      get "session_contexts/edit_settings/:id", to: "session_contexts#edit_settings", as: 'edit_settings'
      post "session_contexts/save_settings", to: "session_contexts#save_settings", as: 'save_settings'

      root 'session_contexts#new'
    end
  end
  get 'errors/not_found'
  get 'errors/internal_server_error'
  get 'dashboard/index'
  get 'logout' => 'dashboard#logout'

  get 'analytics/:type' => proc { [204, {}, ['']] }, :as => 'analytics'

  get 'apps/show/:name(/:type(/:owner))' => 'apps#show', :as => 'app', :defaults => { type: 'sys' }, :constraints => { owner: %r{[^/]+} }
  get 'apps/icon/:name(/:type(/:owner))' => 'apps#icon', :as => 'app_icon', :defaults => { type: 'sys' }, :constraints => { owner: %r{[^/]+} }
  get 'apps/index' => 'apps#index'

  get 'apps/restart' => 'apps#restart' if Configuration.app_sharing_enabled?

  root 'dashboard#index'

  scope 'admin/:type', constraints: Authz::AppDeveloperConstraint do
    resources :products, except: :destroy, param: :name, constraints: { type: /dev|usr/ } do
      nested do
        scope ':context' do
          resources :permissions, only: [:index, :new, :create, :destroy], param: :name
        end
      end
      member do
        patch 'cli/:cmd', to: 'products#cli', as: 'cli'
      end
      collection do
        get 'create_key'
        get 'new_from_git_remote'
        post 'create_from_git_remote'
      end
    end
  end

  if Configuration.can_access_activejobs?
    get '/activejobs' => 'active_jobs#index'
    get '/activejobs/json' => 'active_jobs#json', :defaults => { :format => 'json' }
    delete '/activejobs' => 'active_jobs#delete_job', :as => 'delete_job'
  end

  get '/system-status', to: 'system_status#index', as: 'system_status' if Configuration.can_access_system_status?

  post 'settings', :to => 'settings#update'

  if Configuration.widget_partials_enabled?
    match '/widgets/*widget_path', to: 'widgets#show', via: [:get, :post], as: 'widgets'
  end

  if Configuration.support_ticket_enabled?
    get '/support', to: 'support_ticket#new'
    post '/support', to: 'support_ticket#create'
  end

  get '/custom/:page_code', to: 'custom_pages#index', as: :custom_pages

  match '/404', :to => 'errors#not_found', :via => :all
  match '/500', :to => 'errors#internal_server_error', :via => :all

  get 'module_browser' => 'module_browser#index', :as => 'module_browser'

end

app/app/controllers/projects_controller.rb
# frozen_string_literal: true

# The controller for project pages /dashboard/projects.
class ProjectsController < ApplicationController
  # GET /projects/:id
  def show
    project_id = show_project_params[:id]
    @project = Project.find(project_id)

    if @project.nil?
      respond_to do |format|
        message = I18n.t('dashboard.jobs_project_not_found', project_id: project_id)
        format.html { redirect_to(projects_path, alert: message) }
        format.json { render json: { message: message }, status: :not_found }
      end
    else
      @launchers = Launcher.all(@project.directory)
      @valid_project = Launcher.clusters?
      @valid_scripts = Launcher.scripts?(@project.directory)

      alert_messages = []
      alert_messages << I18n.t('dashboard.jobs_project_invalid_configuration_clusters') unless @valid_project
      if @launchers.any? && !@valid_scripts
        alert_messages << I18n.t('dashboard.jobs_project_invalid_configuration_scripts')
      end
      flash.now[:alert] = alert_messages.join(' ') if alert_messages.any?
      respond_to do |format|
        format.html
        format.json { render :show }
      end
    end
  end

  # GET /projects
  def index
    @projects = Project.all
    @templates = templates
  end

  # GET /projects/new
  def new
    @templates = new_project_params[:template] == 'true' ? templates : []

    @project = Project.new
  end

  # GET /projects/import
  def import
    @project = Project.new
    @projects = Project.possible_imports
  end

  # GET /projects/:id/edit
  def edit
    project_id = show_project_params[:id]
    @project = Project.find(project_id)

    return unless @project.nil?

    redirect_to(projects_path, alert: I18n.t('dashboard.jobs_project_not_found', project_id: project_id))
  end

  # PATCH /projects/:id
  def update
    project_id = show_project_params[:id]
    @project = Project.find(project_id)

    if @project.nil?
      redirect_to(projects_path, alert: I18n.t('dashboard.jobs_project_not_found', project_id: project_id))
      return
    end

    if @project.update(project_params)
      redirect_to projects_path, notice: I18n.t('dashboard.jobs_project_manifest_updated')
    else
      message = if @project.errors[:save].empty?
                  I18n.t('dashboard.jobs_project_validation_error')
                else
                  I18n.t(
                    'dashboard.jobs_project_generic_error', error: @project.collect_errors
                  )
                end
      flash.now[:alert] = message
      render :edit
    end
  end

  # POST /projects
  def create
    @project = Project.new(project_params)

    if @project.save
      redirect_to projects_path, notice: I18n.t('dashboard.jobs_project_created')
    else
      message = if @project.errors[:save].empty?
                  I18n.t('dashboard.jobs_project_validation_error')
                else
                  I18n.t(
                    'dashboard.jobs_project_generic_error', error: @project.collect_errors
                  )
                end
      flash.now[:alert] = message
      @templates = templates if project_params.key?(:template)
      render :new
    end
  end

  # POST /projects/import
  def import_save
    @project = Project.from_directory(project_params[:directory])
    if @project.errors.empty?
      if Project.import_to_lookup(@project)
        redirect_to projects_path, notice: I18n.t('dashboard.jobs_project_imported')
      else
        redirect_to project_import_path, alert: @project.errors.full_messages.join('. ')
      end
    else
      redirect_to project_import_path, alert: @project.errors.full_messages.join('. ')
    end
  end

  # DELETE /projects/:id
  def destroy
    project_id = params[:id]
    @project = Project.find(project_id)

    if @project.nil?
      redirect_to projects_path, notice: I18n.t('dashboard.jobs_project_not_found', project_id: project_id)
      return
    end

    if @project.destroy!
      redirect_to projects_path, notice: I18n.t('dashboard.jobs_project_deleted')
    else
      redirect_to projects_path, notice: I18n.t('dashboard.jobs_project_generic_error', error: @project.collect_errors)
    end
  end

  # GET /projects/:project_id/jobs/:cluster/:jobid
  def job_details
    project = Project.find(job_details_params[:project_id])
    cluster_str = job_details_params[:cluster].to_s
    cluster = OodAppkit.clusters[cluster_str.to_sym]
    render(:status => 404) if cluster.nil?

    hpc_job = project.job(job_details_params[:jobid].to_s, cluster_str)

    @project = project

    render(partial: 'job_details', locals: { job: hpc_job, project: @project })
  end

  # DELETE /projects/:project_id/jobs/:cluster/:jobid
  def delete_job
    @project = Project.find(job_details_params[:project_id])

    cluster_str = job_details_params[:cluster].to_s

    jobid = job_details_params[:jobid]

    if @project.remove_logged_job(jobid.to_s, cluster_str)
      redirect_to(
        project_path(job_details_params[:project_id]),
        notice: I18n.t('dashboard.jobs_project_job_deleted', job_id: jobid)
      )
    else
      redirect_to(
        project_path(job_details_params[:project_id]),
        alert: I18n.t('dashboard.jobs_project_job_not_deleted', jobid: jobid)
      )
    end
  end

  # POST /projects/:project_id/jobs/:cluster/:jobid/stop
  def stop_job
    @project = Project.find(job_details_params[:project_id])
    cluster_str = job_details_params[:cluster].to_s
    cluster = OodAppkit.clusters[cluster_str.to_sym]

    jobid = job_details_params[:jobid]

    hpc_job = @project.job(jobid.to_s, cluster_str)

    begin
      cluster.job_adapter.delete(jobid.to_s) unless hpc_job.status.to_s == 'completed'
      redirect_to(
        project_path(job_details_params[:project_id]),
        notice: I18n.t('dashboard.jobs_project_job_stopped', job_id: jobid)
      )
    rescue StandardError => e
      redirect_to(
        project_path(job_details_params[:project_id]),
        alert: I18n.t('dashboard.jobs_project_generic_error', error: e.message.to_s)
      )
    end
  end

  private

  def templates
    Project.templates.map do |project|
      label = project.title
      data = {
        'data-description' => project.description,
        'data-icon'        => project.icon
      }
      [label, project.directory, data]
    end
  end

  def project_params
    params
      .require(:project)
      .permit(:name, :directory, :description, :icon, :id, :template)
  end

  def show_project_params
    params.permit(:id)
  end

  def new_project_params
    params.permit(:template, :icon, :name, :directory)
  end

  def job_details_params
    params.permit(:project_id, :cluster, :jobid)
  end
end

app/app/helpers/projects_helper.rb
# frozen_string_literal: true

# Helpers for the projects page
module ProjectsHelper
  def render_readme(readme_location)
    file_content = File.read(readme_location)

    if File.extname(readme_location) == '.md'
      markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML)
      markdown_html = markdown.render(file_content).html_safe
      sanitize(markdown_html)
    elsif File.extname(readme_location) == '.txt'
      # simple_format sanitizes its output
      simple_format(file_content)
    end
  end

  def job_details_buttons(status, job, project)
    locals = { project_id: project.id, id: job.id, cluster: job.cluster }
    button_partial = button_category(status)
    render(partial: "projects/buttons/#{button_category(status)}_buttons", locals: locals) unless button_partial.nil?
  end

  def button_category(status)
    case status
    when 'queued_held'
      'held'
    when 'suspended'
      'held'
    else
      status
    end
  end
end

app/app/views/projects/_form.html.erb
<%
  edit_project_action = action_name != "new" && action_name != "create"

  path_selector_id = "project_directory_path_selector"

  path_selector_locals = {
    path_selector_id: path_selector_id,
    show_files: false,
    show_hidden: false,
    file_pattern: '',
    initial_directory: CurrentUser.home,
    table_id: "#{path_selector_id}_table",
    breadcrumb_id: "#{path_selector_id}_breadcrumb",
    button_id: "#{path_selector_id}_button",
    input_field_id: 'project_directory',
    favorites: false,
  }
%>

<div class='card'>
  <%- unless @templates.to_a.empty? -%>
    <div class='card-header'>
      <%= form.select(:template, @templates, { prompt: "--- select template ---" }, required: true, label_class: "h4")%>
    </div>
  <%- end -%>
  <div class='card-group'>
    <div class='card'>
      <div class='card-body'>
        <div class="col">
          <div class="field">
            <%= form.text_field :name, placeholder: I18n.t('dashboard.jobs_project_name_placeholder'),
                    help: I18n.t('dashboard.jobs_project_name_validation') %>
          </div>

          <div class="field">
            <%= form.text_field(:directory, placeholder: I18n.t('dashboard.jobs_project_directory_placeholder'),
                                readonly: edit_project_action,
                                required: false,
                                help: edit_project_action ? '' : I18n.t('dashboard.jobs_project_directory_help_html', root_directory: Project.dataroot.to_s).html_safe,
                                data: { 'path-selector': true })%>

            <button type="button" class="btn btn-primary mt-2" data-bs-toggle="modal" data-bs-target="#<%= path_selector_id %>">
              <%= I18n.t('dashboard.select_path') %>
            </button>

            <%= render(partial: 'shared/path_selector_table', locals: path_selector_locals ) %>
          </div>

          <div class="field">
            <%= form.text_area :description, placeholder: I18n.t('dashboard.jobs_project_description_placeholder') %>
          </div>
        </div>
      </div>
      </div>
      <div class="card">
      <div class='card-body'>
        <div class="col">
          <div class="field">
          <%= javascript_include_tag('icon_picker', nonce: true, type: 'module') %>
          <%= form.text_field :icon, placeholder: "cog", id: "product_icon_select", value: @project.icon_class %>
            <% if @project.icon =~ /(fa[bsrl]?):\/\/(.*)/ %>
              <% icon = $2; style = $1 %>
              <p class="text-center">
                <%= fa_icon(icon, fa_style: style, id: "product_icon")  %>
              </p>
            <% else %>
              <p class="text-center">
                <%= fa_icon("cog", fa_style: "fas", id: "product_icon") %>
              </p>
            <% end %>
              <ul id="icon_picker_list">
              </ul>
          </div>
        </div>
      </div>
      </div>
    </div>
  </div>
  <br>
  <p>
    <%= form.submit 'Save', class: 'btn btn-primary', title: 'Save project' %>
    <%= form.button 'Reset', type: :reset, class: 'btn btn-default', title: 'Clear form fields' %>
    <%= link_to 'Back', projects_path, class: 'btn btn-default', title: 'Return to projects page' %>
  </p>
</div>

app/app/views/projects/_job_details.html.erb
<%- 
  id = "job_#{job.cluster}_#{job.id}"
-%>

<div id="<%= id %>" data-job-poller="true"
  data-job-cluster="<%= job.cluster %>"
  data-job-id="<%= job.id %>"
  data-job-status="<%= job.status.to_s %>"
  class="col-md-4">

  <div class="d-flex justify-content-center">
    <div class="spinner-border" role="status">
      <span class="sr-only">Loading...</span>
    </div>
  </div>

</div>

app/app/views/projects/_job_details.turbo_stream.erb
<%- 
  id = "job_#{job.cluster}_#{job.id}"
-%>

<turbo-stream action="replace" target="<%= id %>" data-job-status="<%= job.status %>">
  <template>
    <%= render(partial: 'job_details_content', locals: { job: job, project: project }, :formats=>[:html]) %>
  </template>
</turbo-stream>

app/app/views/projects/_job_details_content.html.erb
<%- 
  id = "job_#{job.cluster}_#{job.id}"
-%>

<div>
  <button class="badge <%= status_class(job.status.to_s) %> rounded-pill border-0 btn" type="button" data-bs-toggle="collapse" data-bs-target="#<%= id %>_data">
    <span>
      <%= job.id %> <%= status_text(job.status.to_s) %>
    </span>
  </button>
  <div class="collapse" id="<%= id %>_data">
    <div class="card card-body">
      <table class="table table-bordered table-sm m-0 mb-2">
        <% job.to_human_display.each do |name, value| %>
          <tr>
            <td><strong><%= name %></strong></td>
            <td><%= value %></td>
          </tr>
        <% end %>
      </table>
      <div class="d-flex flex-row-reverse mt-2 mx-2">
        <%= job_details_buttons(job.status.to_s, job, project) %>
      </div>
    </div>
  </div>
</div>

app/app/views/projects/edit.html.erb
<div class='page-header text-center pb-3'>
  <h1>
    Editing: <%= @project.title %>
  </h1>
</div>

<%= bootstrap_form_for(@project, url: project_path, method: :patch) do |form| %>
  <%= render partial: "form", locals: { form: form }%>
<% end %>

app/app/views/projects/import.html.erb
<%= javascript_include_tag('projects_import', nonce: true, type: 'module') %>

<div class='page-header text-center pb-3'>
  <h1>
    Import a Shared Project
  </h1>
</div>

<%
  path_selector_id = "project_directory_path_selector"

  path_selector_locals = {
    path_selector_id: path_selector_id,
    show_files: false,
    show_hidden: false,
    file_pattern: '',
    initial_directory: CurrentUser.home,
    table_id: "#{path_selector_id}_table",
    breadcrumb_id: "#{path_selector_id}_breadcrumb",
    button_id: "#{path_selector_id}_button",
    input_field_id: 'project_directory',
    favorites: false,
  }
%>

<%= bootstrap_form_for(@project, url: project_import_save_path, method: :post) do |form| %>
<div class='card'>
  <div class='card-group'>
    <div class='card'>
      <div class='card-body'>
        <div class="col">
          <div class="field">
            <%= form.text_field(:directory, placeholder: I18n.t('dashboard.jobs_project_directory_placeholder'),
                                data: { 'path-selector': true }) %>

            <button type="button" class="btn btn-primary mt-2" data-bs-toggle="modal" data-bs-target="#<%= path_selector_id %>">
              <%= I18n.t('dashboard.select_path') %>
            </button>

            <%= render(partial: 'shared/path_selector_table', locals: path_selector_locals ) %>
          </div>
        </div>
      </div>
      </div>
    </div>
  </div>
  <br>
  <p>
    <%= form.submit I18n.t('dashboard.import'), class: 'btn btn-primary', title: 'Save project' %>
    <%= form.button I18n.t('dashboard.reset'), type: :reset, class: 'btn btn-default', title: 'Clear form fields' %>
    <%= link_to I18n.t('dashboard.back'), projects_path, class: 'btn btn-default', title: 'Return to projects page' %>
  </p>
</div>
<% end %>

<div class='card'>
  <div class='card-group'>
    <div class='card'>
      <div class='card-body'>
        <strong>
          <%= label :directory, I18n.t('dashboard.jobs_select_directory_placeholder') %>
        </strong>
        <div class="d-flex flex-wrap justify-content-start">
          <% @projects.each do |project| %>
            <%= button_to project_import_save_path, method: :post, 
                params: { project: { directory: project.directory } }, 
                class: 'btn p-0 border-0 bg-transparent' do %>
              <div id="<%= project.id %>" class="col-md-3 project-icon project-card" style="width: 150px;">
                <div class="text-center d-flex justify-content-center">
                  <strong>
                    <%= icon_tag(URI.parse(project.icon)) %>
                    <%= content_tag(:p, project.title) %>
                  </strong>
                </div>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>  

app/app/views/projects/index.html.erb
<div class='page-header text-center'>
  <h1>Project Manager</h1>
  <small class="text-muted">This is a preview of the new 'Project Manager'</small>
</div>

<div class="row mt-3">
  <div class="col-md-9">
    <div class="row">
      <% @projects.each do |project| %>
        <div id="<%= project.id %>" class="col-md-3 project-icon project-card">
          <%= link_to(project_path(project.id), class: 'text-dark') do %>
            <div class="text-center d-flex justify-content-center">
              <strong>
                <%= icon_tag(URI.parse(project.icon)) %>
                <%= content_tag(:p, project.title) %>
              </strong>
            </div>
            <div class="row">
              <div class="col">
                <%= button_to 'Delete', project_path(project.id), class: 'btn btn-danger w-100 mb-1', method: 'delete',
                    form: { class: 'button_to d-flex justify-content-center' },
                    data: { confirm: I18n.t('dashboard.jobs_project_delete_project_confirmation') }
                %>
              </div>
              <div class="col">
                <%= button_to 'Edit', edit_project_path(project.id), class: 'btn btn-info w-100', method: 'get',
                    form: { class: 'd-flex justify-content-center' },
                    title: 'Edit project directory'
                %>  
              </div>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
  <div class="col-md-3">

      <div class="mt-5 justify-content-center text-center project-icon">
        <%= link_to(new_project_path,
                      title: I18n.t('dashboard.jobs_create_blank_project'),
                      class: 'text-dark btn btn-link') do
        %>
          <div class="text-center d-flex justify-content-center">
            <strong>
              <%= icon_tag(URI.parse("fas://file-medical")) %><br>
              <%= I18n.t('dashboard.jobs_create_blank_project') %>
            </strong>
          </div>
        <% end %>
      </div>

      <%- if @templates.size.positive? -%>
        <div class="mt-5 justify-content-center text-center project-icon">
          <%= link_to(new_project_path({template: true}),
                        title: I18n.t('dashboard.jobs_create_template_project'),
                        class: 'text-dark btn btn-link') do
          %>
            <div class="text-center d-flex justify-content-center">
              <strong>
                <%= icon_tag(URI.parse("fas://copy")) %><br>
                <%= I18n.t('dashboard.jobs_create_template_project') %>
              </strong>
            </div>
          <% end %>
        </div> 
      <%- end -%>

      <div class="mt-5 justify-content-center text-center project-icon">
        <%= link_to(project_import_path,
                      title: I18n.t('dashboard.jobs_import_shared_project'),
                      class: 'text-dark btn btn-link') do
        %>
          <div class="text-center d-flex justify-content-center">
            <strong>
              <%= icon_tag(URI.parse("fas://file-import")) %><br>
              <%= I18n.t('dashboard.jobs_import_shared_project') %>
            </strong>
          </div>
        <% end %>
      </div>

  </div>
</div>

app/app/views/projects/new.html.erb
<%= javascript_include_tag('projects_new', nonce: true, type: 'module') %>

<div class='page-header text-center'>
  <h1>New Project</h1>
</div>

<br>

<%= bootstrap_form_for(@project, url: projects_path) do |form| %>
  <%= render partial: "form", locals: { form: form }%>
<% end %>

app/app/views/projects/show.html.erb
<%= javascript_include_tag 'projects', nonce: true %>
<%-
  disabled = !@valid_project
  disabled_class = disabled ? 'disabled' : ''
-%>

<div class="d-none" id="project_config" data-project-id="<%= @project.id %>">
</div>

<div class='row'>
  <div class="col-2 align-self-center justify-content-left d-flex">
    <%= link_to 'Back', projects_path, class: 'btn btn-default align-self-start', title: 'Return to projects page' %>
  </div>


  <div class='page-header text-center col-8'>
    <h1 class="my-2 h3"><%= @project.title %></h1>

    <small class="text-muted">This is a preview of the new 'Project Manager'</small>
  </div>
</div>

<div class="row mb-3">
  <div class="col-md-2 mt-3">
    <div class="list-group bg-white rounded">
      <a class="list-group-item list-group-item-action bg-light font-weight-bold list-toggler"
          data-bs-toggle="collapse" data-bs-target="#launcher_list"
          aria-expanded="true" aria-controls="launcher_list">
        <span class="lead fw-bolder"><%= t('dashboard.jobs_launchers') %></span>
      </a>

      <div id="launcher_list" class="collapse show">
        <%- @launchers.each do |launcher| -%>
        <div class="list-group-item list-group-item-action" id="launcher_<%= launcher.id %>">
          <div class="row launcher-item">
            <div class="col launcher-title">
              <%= launcher.title %>
            </div>
          </div>

          <%= render(partial: 'launcher_buttons', locals: { launcher: launcher }) %>
        </div>
        <%- end -%>
      </div>

      <a class="list-group-item list-group-item-action text-info font-weight-bold"
        href="<%= new_project_launcher_path(@project.id) %>">
        <%= t('dashboard.jobs_new_launcher') %>
      </a>
    </div>
  </div>
  
  <div class="col-md-4">
    <div class="border border-2 p-3 mt-3 mb-5 bg-white rounded">
      <div class="row">
        <h2 class="lead fw-bolder d-flex justify-content-center">Active Jobs</h2>
        <%= render(partial: 'job_details', collection: @project.active_jobs, as: :job, locals: { project: @project }) %>
      </div>

      <div class="row">
        <h2 class="lead fw-bolder d-flex justify-content-center">Completed Jobs</h2>
        <div id="completed_jobs" class="row">
          <%- @project.completed_jobs.each do |job| -%>
          <div class="col-md-4" id="<%= "job_#{job.cluster}_#{job.id}" %>">
            <%= render(partial: 'job_details_content', locals: { job: job, project: @project }) %>
          </div>
          <%- end -%>
        </div>
      </div>
    </div>
  </div>
  <div class="col-md-6">
    <div id="directory_browser" class="border border-2 p-3 mt-3 mb-5 bg-white rounded">
      <h2 class="lead fw-bolder d-flex justify-content-center"><%= "#{t('dashboard.project')} #{t('dashboard.directory')}" %>: &nbsp<i><%= @project.id %></i></h2>
      <hr>
      <%= turbo_frame_tag 'project_directory', 
            src: directory_frame_path(
              files: @files,
              path: @project&.directory
           ) do
      %>
        <div class="d-flex justify-content-center">
          <div id="loading-icon" class="spinner-border rem-5" role="status">
            <span class="sr-only">Loading...</span> 
          </div>
        </div>
      <%- end -%>
    </div>
  </div>
</div>

<% unless @project.readme_path.nil? %>
  <div class="card">
    <div class="card-header">
      <button class="btn btn-default fa fa-chevron-right" type="button" data-bs-toggle="collapse" data-bs-target="#readme" aria-expanded="true" aria-controls="readme"></button>
      <%= File.basename(@project.readme_path) %>
    </div>
    <div class="card-body collapse show" id="readme">
      <%= render_readme(@project.readme_path)  %>
    </div>
  </div>
<% end %>

app/app/views/projects/submit.html.erb
<h1>Jobs#submit</h1>

app/app/views/projects/update.html.erb
<h1>Jobs#update</h1>
<p>Find me in app/views/jobs/update.html.erb</p>