app/config/routes.rb
require 'authz/app_developer_constraint'

Rails.application.routes.draw do
  if Configuration.can_access_projects?
    get 'projects/import' => 'projects#import', :as => 'project_import'
    post 'projects/import' => 'projects#import_save', :as => 'project_import_save'

    resources :projects do
      root 'projects#index'
      get '/jobs/:cluster/:jobid' => 'projects#job_details', :defaults => { :format => 'turbo_stream' }, :as => 'job_details'
      delete '/jobs/:cluster/:jobid' => 'projects#delete_job', :as => 'delete_job'
      post '/jobs/:cluster/:jobid/stop' => 'projects#stop_job', :as => 'stop_job'

      resources :launchers do
        post 'submit', on: :member
        post 'save', on: :member
      end
    end
  end

  if Configuration.can_access_files?
    constraints(->(request) { request.params[:fs].to_s.match?(%r{^(?!(edit|api))[^/]+$}) }) do
      get 'files/:fs(/*filepath)' => 'files#fs', :defaults => { :fs => 'fs', :format => 'html' }, :format => false,
          :as => :files
      put 'files/:fs/*filepath' => 'files#update', :format => false, :defaults => { :fs => 'fs', :format => 'json' }

      get 'files/api/v1/:fs(/*filepath)' => 'files#fs', :defaults => { :fs => 'fs', :format => 'html' },
          :format => false
      put 'files/api/v1/:fs/*filepath' => 'files#update', :format => false,
          :defaults => { :fs => 'fs', :format => 'json' }
    end
    post 'files/upload/:fs' => 'files#upload', :defaults => { :fs => 'fs' } if Configuration.upload_enabled?

    get 'files', to: redirect("files/fs#{Dir.home}")
    get 'files/fs', to: redirect("files/fs#{Dir.home}")
    get 'frames/directory_frame' => 'files#directory_frame', as: 'directory_frame'
    
    resources :transfers, only: [:show, :create, :destroy]
  end

  if Configuration.can_access_file_editor?
    get 'files/edit/:fs/*filepath' => 'files#edit', :defaults => { :fs => 'fs', :path => '/', :format => 'html' },
        :format => false
    get 'files/edit/:fs' => 'files#edit', :defaults => { :fs => 'fs', :path => '/', :format => 'html' },
        :format => false
  end

  namespace :batch_connect do
    resources :sessions, only: [:index, :destroy]
    post 'sessions/:id/cancel', to: 'sessions#cancel', as: 'cancel_session'
    scope '*token', constraints: { token: %r{((usr/[^/]+)|dev|sys)/[^/]+(/[^/]+)?} } do
      resources :settings, only: [:show, :destroy]
      resources :session_contexts, only: [:new, :create]
      get "session_contexts/edit_settings/:id", to: "session_contexts#edit_settings", as: 'edit_settings'
      post "session_contexts/save_settings", to: "session_contexts#save_settings", as: 'save_settings'

      root 'session_contexts#new'
    end
  end
  get 'errors/not_found'
  get 'errors/internal_server_error'
  get 'dashboard/index'
  get 'logout' => 'dashboard#logout'

  get 'analytics/:type' => proc { [204, {}, ['']] }, :as => 'analytics'

  get 'apps/show/:name(/:type(/:owner))' => 'apps#show', :as => 'app', :defaults => { type: 'sys' }, :constraints => { owner: %r{[^/]+} }
  get 'apps/icon/:name(/:type(/:owner))' => 'apps#icon', :as => 'app_icon', :defaults => { type: 'sys' }, :constraints => { owner: %r{[^/]+} }
  get 'apps/index' => 'apps#index'

  get 'apps/restart' => 'apps#restart' if Configuration.app_sharing_enabled?

  root 'dashboard#index'

  scope 'admin/:type', constraints: Authz::AppDeveloperConstraint do
    resources :products, except: :destroy, param: :name, constraints: { type: /dev|usr/ } do
      nested do
        scope ':context' do
          resources :permissions, only: [:index, :new, :create, :destroy], param: :name
        end
      end
      member do
        patch 'cli/:cmd', to: 'products#cli', as: 'cli'
      end
      collection do
        get 'create_key'
        get 'new_from_git_remote'
        post 'create_from_git_remote'
      end
    end
  end

  if Configuration.can_access_activejobs?
    get '/activejobs' => 'active_jobs#index'
    get '/activejobs/json' => 'active_jobs#json', :defaults => { :format => 'json' }
    delete '/activejobs' => 'active_jobs#delete_job', :as => 'delete_job'
  end

  get '/system-status', to: 'system_status#index', as: 'system_status' if Configuration.can_access_system_status?

  post 'settings', :to => 'settings#update'

  if Configuration.widget_partials_enabled?
    match '/widgets/*widget_path', to: 'widgets#show', via: [:get, :post], as: 'widgets'
  end

  if Configuration.support_ticket_enabled?
    get '/support', to: 'support_ticket#new'
    post '/support', to: 'support_ticket#create'
  end

  get '/custom/:page_code', to: 'custom_pages#index', as: :custom_pages

  match '/404', :to => 'errors#not_found', :via => :all
  match '/500', :to => 'errors#internal_server_error', :via => :all

  get 'module_browser' => 'module_browser#index', :as => 'module_browser'

end

app/app/models/batch_connect/settings.rb
module BatchConnect
  # An Interactive Application saved parameters from the form.
  class Settings
    include ActiveModel::Model

    attr_reader :token, :name, :values

    def initialize(token, name, values)
      @token = token.to_s
      @name = name.to_s
      @values = values.to_h
    end

    def app
      @app ||= BatchConnect::App.from_token token
    end

    def outdated?
      outdated = false
      # CHECK IF THERE ARE NEW ATTRIBUTES NOT IN THE VALUES HASH
      app.attributes.each do |attribute|
        outdated = true unless values.key?(attribute.id.to_sym)
      end
      # CHECK IF THERE ARE OLD VALUES NO LONGER IN THE APP ATTRIBUTES STILL IN THE VALUES HASH
      values.each_key do |attribute_id|
        outdated = true if app.attributes.select { |attribute| attribute.id.to_sym == attribute_id }.empty?
      end

      outdated
    end

  end
end

app/app/controllers/batch_connect/session_contexts_controller.rb
# frozen_string_literal: true

# The controller for creating batch connect sessions.
module BatchConnect
  class SessionContextsController < ApplicationController
    include BatchConnectConcern
    include UserSettingStore
    include EncryptedCache

    # GET /batch_connect/<app_token>/session_contexts/new
    def new
      set_app
      set_render_format
      set_session_context
      set_prefill_templates

      session_id = params[:session_id]
      valid_session = session_id && BatchConnect::Session.exist?(session_id)

      if @app.valid?
        begin
          app_parameters_file = valid_session ? BatchConnect::Session.find(session_id).user_defined_context_file : cache_file
          @app.update_session_with_cache(@session_context, app_parameters_file)
        rescue StandardError => e
          flash.now[:alert] = t('dashboard.batch_connect_form_attr_cache_error', error_message: e.message)
        end
      else
        @session_context = nil # do not display session context form
        flash.now[:alert] = @app.validation_reason
      end

      set_app_groups
      set_saved_settings
      set_my_quotas
    end

    # POST /batch_connect/<app_token>/session_contexts
    # POST /batch_connect/<app_token>/session_contexts.json
    def create
      set_app
      set_render_format
      set_session_context

      # Read in context from form parameters
      @session_context.attributes = session_contexts_param

      @session = BatchConnect::Session.new
      respond_to do |format|
        if @session.save(app: @app, context: @session_context, format: @render_format)
          cache_data = encypted_cache_data(app: @app, data: @session_context.to_openstruct.to_h)
          cache_file.write(cache_data.to_json) # save context to cache file
          save_template
          # We need to set the prefill templates only after storing the new one
          # so that the new one is included / updated in the list
          set_prefill_templates

          format.html do
            redirect_to batch_connect_sessions_url,
                        notice: t('dashboard.batch_connect_sessions_status_blurb_create_success')
          end
          format.json { head :no_content }
        else
          set_prefill_templates
          format.html do
            set_app_groups
            set_saved_settings
            render :new
          end
          format.json { render json: @session_context.errors, status: :unprocessable_entity }
        end
      end
    end

    # GET /batch_connect/<app_token>/session_contexts/edit_settings/<settings_name>
    def edit_settings
      set_app
      set_render_format
      set_session_context
      set_prefill_templates

      @template_name = params[:id].to_sym
      settings = @prefill_templates[@template_name]
      if settings.nil?
        redirect_to new_batch_connect_session_context_path(token: @app.token),
                    alert: t('dashboard.bc_saved_settings.missing_settings')
        return
      end

      @session_context.update_with_cache(settings)

      set_app_groups
      set_saved_settings
      set_my_quotas

      render :new
    end

    # POST /batch_connect/<app_token>/session_contexts/save_settings
    def save_settings
      set_app
      set_render_format
      set_session_context

      # Read in context from form parameters
      @session_context.attributes = session_contexts_param

      template_name = params[:template_name]
      save_template

      redirect_to batch_connect_setting_path(token: @app.token, id: template_name),
                  notice: t('dashboard.bc_saved_settings.saved_message', settings_name: template_name)
    end

    private

    # Set the app from the token
    def set_app
      @app = BatchConnect::App.from_token params[:token]
    end

    # Set list of app lists for navigation
    def set_app_groups
      @sys_app_groups = bc_sys_app_groups
      @usr_app_groups = bc_usr_app_groups
      @dev_app_groups = bc_dev_app_groups
      @apps_menu_group = bc_custom_apps_group
    end

    # Set the all the saved settings to render the navigation
    def set_saved_settings
      @bc_saved_settings = all_bc_templates
    end

    # Set the session context from the app
    def set_session_context
      @session_context = @app.build_session_context
    end

    # Set the rendering format for displaying attributes
    def set_render_format
      @render_format = @app.clusters.first.job_config[:adapter] unless @app.clusters.empty?
    end

    # Set the rendering format for displaying attributes
    def set_prefill_templates
      @prefill_templates ||= bc_templates(@app)
    end

    def save_template
      return unless params[:save_template].present? && params[:save_template] == 'on' && params[:template_name].present?

      save_bc_template(@app, params[:template_name], @session_context.to_h)
    end

    # Only permit certian parameters
    def session_contexts_param
      if params[:batch_connect_session_context].present?
        params.require(:batch_connect_session_context).permit(@session_context.attributes.keys)
      end
    end

    # Store session context into a cache file
    # @return [Pathname] the cachefile path
    def cache_file
      BatchConnect::Session.cache_root.tap do |p|
        p.mkpath unless p.exist?
      end.join(@app.cache_file)
    end
  end
end

app/app/helpers/batch_connect/session_contexts_helper.rb
# Helper for creating new batch connect sessions.
module BatchConnect::SessionContextsHelper
  def create_widget(form, attrib, format: nil, hide_excludable: true, hide_fixed: true)
    return '' if hide_fixed && attrib.fixed?
    return '' if attrib.hide_when_empty? && attrib.value.blank?

    widget = attrib.widget
    field_options = attrib.field_options(fmt: format)
    all_options = attrib.all_options(fmt: format)

    if attrib.fixed?
      return render :partial => "batch_connect/session_contexts/fixed", :locals => { form: form, attrib: attrib, field_options: field_options, format: format }
    end

    rendered =  case widget
                when 'select'
                  form.select(attrib.id, attrib.select_choices(hide_excludable: hide_excludable), field_options, attrib.html_options)
                when 'resolution_field'
                  resolution_field(form, attrib.id, all_options)
                when 'check_box'
                  form.form_group attrib.id, help: field_options[:help] do
                    form.check_box attrib.id, all_options, attrib.checked_value, attrib.unchecked_value
                  end
                when 'radio', 'radio_button'
                  form.form_group attrib.id, help: field_options[:help] do
                    opts = {
                      label:   label_tag(attrib.id, attrib.label),
                      checked: (attrib.value.presence || attrib.field_options[:checked])
                    }
                    form.collection_radio_buttons(attrib.id, attrib.select_choices, :second, :first, **opts)
                  end
                when 'path_selector'
                  form.form_group(attrib.id) do
                    render(partial: 'path_selector', locals: { form: form, attrib: attrib, field_options: field_options })
                  end
                when 'file_attachments'
                  render :partial => "batch_connect/session_contexts/file_attachments", :locals => { form: form, attrib: attrib, field_options: field_options }
                else
                  form.send widget, attrib.id, all_options
                end
    header = sanitize(OodAppkit.markdown.render(attrib.header))
    "#{header}#{rendered}".html_safe

  end

  def resolution_field(form, id, opts = {})
    content_tag(:div, id: "#{id}_group", class: "mb3") do
      concat form.label(id, opts[:label])
      concat form.hidden_field(id, id: "#{id}_field")
      concat(
        content_tag(:div, class: "row mb-3") do
          concat (
            content_tag(:div, class: "col-sm-6") do
              concat (
                content_tag(:div, class: "input-group") do
                  concat (content_tag(:div, class: "input-group-prepend") do
                    content_tag(:div, "width", class: "input-group-text")
                  end)
                  concat number_field_tag("#{id}_x_field", nil, class: "form-control", min: 100, required: opts[:required])
                  concat (content_tag(:div, class: "input-group-append") do
                    content_tag(:div, "px", class: "input-group-text")
                  end)
                end
              )
            end
          )
          concat (
            content_tag(:div, class: "col-sm-6") do
              concat (
                content_tag(:div, class: "input-group") do
                  concat (content_tag(:div, class: "input-group-prepend") do
                    content_tag(:div, "height", class: "input-group-text")
                  end)
                  concat number_field_tag("#{id}_y_field", nil, class: "form-control", min: 100, required: opts[:required])
                  concat (content_tag(:div, class: "input-group-append") do
                    content_tag(:div, "px", class: "input-group-text")
                  end)
                end
              )
            end
          )
        end
      )
      concat content_tag(:span, opts[:help], class: "help-block") if opts[:help]
      concat button_tag(t('dashboard.batch_connect_form_reset_resolution'), id: "#{id}_reset", type: "button", class: "btn btn-light")
      concat(
        content_tag(:script) do
          <<-EOT.html_safe
            (function() {
              // Target elements
              var $target  = $('##{id}_field');
              var $targetX = $('##{id}_x_field');
              var $targetY = $('##{id}_y_field');
              var $targetR = $('##{id}_reset');

              // Helper methods
              var setX = function(x) {
                y = getY();
                $target.val(x + 'x' + y);
                $targetX.val(x);
              };
              var setY = function(y) {
                x = getX();
                $target.val(x + 'x' + y);
                $targetY.val(y);
              };
              var getX = function() {
                return $target.val().split('x')[0];
              };
              var getY = function() {
                return $target.val().split('x')[1];
              };
              var resetXY = function() {
                setX(window.screen.width  * 0.8 | 0);
                setY(window.screen.height * 0.8 | 0);
              };

              // Set defaults if not already set
              if ( !$target.val() ) {
                resetXY();
              } else {
                setX(getX());
                setY(getY());
              }

              // Event listeners
              $targetX.change(function() {
                setX($(this).val());
              });
              $targetY.change(function() {
                setY($(this).val());
              });
              $targetR.click(function() {
                resetXY();
              });
            })();
          EOT
        end
      )
    end
  end

  def pathselector_favorites(favorites)
    # If favorites is false, return nil
    if favorites.nil?
      OodFilesApp.new.favorite_paths.reject(&:remote?)
    elsif favorites
      favorites.map { |f| FavoritePath.new(f) }
    end
  end
end

app/app/helpers/batch_connect/settings_helper.rb
# Utility methods related to saved_settings
module BatchConnect::SettingsHelper
  include UserSettingStore

  def all_saved_settings
    all_bc_templates.sort.flat_map do |app_token, app_saved_settings|
      app_saved_settings.sort.map do |settings_name, settings_values|
        BatchConnect::Settings.new(app_token, settings_name, settings_values)
      end
    end
  end

end

app/app/views/batch_connect/session_contexts/_favorites.html.erb
<li role='button'
  class='clickable text-wrap list-group-item list-group-item-action'
  data-api-url=<%= files_path(path.to_s, fs: path.filesystem) %>>
  <span class='fa fa-folder'>&nbsp;</span><%= path %>
</li>

app/app/views/batch_connect/session_contexts/_file_attachments.html.erb
<% has_error = !form.object.errors[attrib.id].empty? %>
<div class="form-group">
  <label class="form-label" for="<%= "#{form.object.class.name.underscore}_#{attrib.id}" %>"><%= attrib.label %></label>
  <p class="<%= has_error ? 'is-invalid' : '' %>" data-bs-toggle="attachments-error" id="<%= "#{form.object.class.name.underscore}_#{attrib.id}" %>">Click the box to attach a file. Screenshots or other files can help troubleshoot your problem.</p>
  <% if has_error %>
    <div class="invalid-feedback">
      <p><%= form.object.errors[attrib.id].join(", ") %></p>
    </div>
  <% end %>
  <div id="attachments-container"></div>

  <p class="attachments-add" data-bs-toggle="attachments-add"><i class="far fa-plus-square" title="Add attachment"></i> <span>Add attachment</span></p>
</div>

app/app/views/batch_connect/session_contexts/_fixed.html.erb
<%-
  all_options = attrib.all_options(fmt: format)
  all_options[:readonly] = true
%>

<%= form.text_field(attrib.id, all_options) %>

app/app/views/batch_connect/session_contexts/_form.html.erb
<%= sanitize OodAppkit.markdown.render(@app.form_header) %>

<%= render "prefill_templates" if Configuration.bc_saved_settings? %>

<%= bootstrap_form_for(@session_context, html: { autocomplete: "off" }) do |f| %>
  <% f.object.each do |attrib| %>
    <%= create_widget(f, attrib, format: @render_format) %>
  <% end %>

  <%- if Configuration.bc_saved_settings? -%>
  <div class="mb-3 form-check">
      <input class="form-check-input align-self-center" name="save_template" type="checkbox" id="batch_connect_session_save_template" <%= @template_name ? 'checked' : '' %>>
      <label class="form-check-label align-self-center" for="batch_connect_session_save_template"><%= t('dashboard.batch_connect_form_save') %></label>
  </div>

  <div class="mb-3 d-flex">
    <input class="form-control w-50 me-2" name="template_name" value="<%= @template_name %>" type="text" id="batch_connect_session_template_name" aria-label="<%= t('dashboard.batch_connect_form_template_name_label') %>" readonly>
    <%= f.submit t('dashboard.batch_connect_form_save_submit'), id: 'batch_connect_session_save_template_submit', class: "ms-auto btn btn-primary", formaction: batch_connect_save_settings_path(token: @app.token), disabled: @template_name ? false : true %>
  </div>
  <%- end -%>

  <div class="d-grid gap-2">
    <%= f.submit t('dashboard.batch_connect_form_launch'), class: "btn btn-primary" %>
  </div>
<% end %>

<%= javascript_include_tag('batch_connect_session_contexts', nonce: true) %>

<% @app.custom_javascript_files.each do |jsfile| %>
  <%= javascript_tag "(function(){\n" + jsfile.read + "\n}());" %>
<% end %>

app/app/views/batch_connect/session_contexts/_path_selector.html.erb
<%
  input_field_id = "#{form.object_name}_#{attrib.id}"
  path_selector_id = "#{input_field_id}_path_selector"
  options =  { data: { 'path-selector': true }}.merge(field_options)

  locals = {
    show_hidden: field_options.fetch(:show_hidden, false),
    show_files: field_options.fetch(:show_files, true),
    file_pattern: field_options.fetch(:file_pattern, ''),
    initial_directory: field_options.fetch(:directory, CurrentUser.home),
    favorites: pathselector_favorites(field_options.try(:[], :favorites)),

    path_selector_id: path_selector_id,
    table_id: "#{path_selector_id}_table",
    breadcrumb_id: "#{path_selector_id}_breadcrumb",
    button_id: "#{path_selector_id}_button",
    input_field_id: input_field_id
  }
%>

<%= form.text_field(attrib.id, class: 'form-control', **options) %>

<button type="button" class="btn btn-primary mt-2" data-bs-toggle="modal" data-bs-target="#<%= path_selector_id %>">
  <%= I18n.t('dashboard.select_path') %>
</button>

<%= render(partial: 'shared/path_selector_table', locals: locals ) %>

app/app/views/batch_connect/session_contexts/_prefill_templates.html.erb
<%- unless @prefill_templates.empty? -%>
  <div class="form-group">
    <label class="control-label"><%= t('dashboard.batch_connect_form_prefill') %></label>
    <select class="form-control selectpicker" id="batch_connect_session_prefill_template">
      <option selected value> -- <%= t('dashboard.batch_connect_form_select_template') %> -- </option>
      <% @prefill_templates.each do |name, template_data| %>
        <option value="<%= template_data.to_json %>"><%= name %></option>
      <% end %>
    </select>
  </div>
<%- end -%>

<div class="modal fade" id="batch_connect_session_template_form_error_modal" tabindex="-1" role="dialog" aria-labelledby="formPrefillErrorLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <div class="modal-title h5" id="formPrefillErrorLabel"><%= t('dashboard.batch_connect_form_prefill_error') %></div>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="<%= t('dashboard.close') %>"></button>
      </div>
      <div class="modal-body" id="batch_connect_session_template_form_error_modal_body"></div>
    </div>
  </div>
</div>

<div class="modal fade" id="chooseTemplateName" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <div class="modal-title h5" id="chooseTemplateNameLabel"><%= t('dashboard.batch_connect_form_choose_template_name') %></div>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="<%= t('dashboard.close') %>"></button>
      </div>
      <div class="modal-body">
        <select class="form-control selectpicker" id="modal_input_template_name">
          <option selected value> -- <%= t('dashboard.batch_connect_form_save_new_template') %> -- </option>
          <% @prefill_templates.each do |name, template_data| %>
            <option value="<%= name %>"><%= name %></option>
          <% end %>
        </select>
        <input type="text" class="form-control mt-3" id="modal_input_template_new_name" placeholder="<%= t('dashboard.batch_connect_form_type_new_name') %>">
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" id="batch_connect_session_template_choose_name_button"><%= t('dashboard.save') %></button>
        <button type="button" class="btn btn-danger" data-bs-dismiss="modal"><%= t('dashboard.close') %></button>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="batch_connect_session_template_name_error_modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <div class="modal-title h5"><%= t('dashboard.batch_connect_form_type_new_name_error') %></div>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
    </div>
  </div>
</div>

app/app/views/batch_connect/session_contexts/new.html.erb
<% content_for :title, "#{@app.title} - #{@user_configuration.dashboard_title}" %>

<%= render partial: 'batch_connect/shared/breadcrumb',
locals: {
  links: [
  {
    text: t('dashboard.breadcrumbs_home'),
    href: root_path
  },
  {
    text: t('dashboard.breadcrumbs_my_sessions'),
    href: batch_connect_sessions_path
  },
  {
    text: @app.title
  }]
}
%>

<%- if @session && @session.errors.any? -%>
  <div class="alert alert-danger alert-dismissible" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>

    <% @session.errors.each do |error| %>
      <% if error.attribute == :submit %>
        <h4><%= t('dashboard.batch_connect_sessions_errors_submission') %></h4>
        <pre><%= error.message %></pre>
      <% elsif error.attribute == :stage %>
        <h4><%= t('dashboard.batch_connect_sessions_errors_staging') %></h4>
        <pre><%= error.message %></pre>
      <% else %>
        <h4><%= error.attribute %></h4>
        <pre><%= error.message %></pre>
      <% end %>
    <% end %>

    <ul>
      <% if @session.errors.include?(:submit) %>
      <li>
        <%= t('dashboard.batch_connect_sessions_error_invalid_job_name_html') %>
      </li>
      <% end %>
      <li>
        <%= t('dashboard.batch_connect_sessions_data_html',
            title: @app.title,
            data_link_tag: link_to(
              t('dashboard.batch_connect_sessions_staged_root'),
              OodAppkit.files.url(path: @session.staged_root).to_s,
              target: "_blank")
            )
            %>
      </li>
    </ul>
  </div>
<%- end -%>

<div class="row">
  <div class="col-md-3">
    <%= render partial: 'batch_connect/shared/saved_settings_menu' %>
    <%=
      render(
        partial: "batch_connect/shared/app_menu",
        locals: {
          sys_app_groups: @sys_app_groups,
          usr_app_groups: @usr_app_groups,
          dev_app_groups: @dev_app_groups,
          apps_menu_group: @apps_menu_group,
          current_url: new_batch_connect_session_context_path(token: @app.token)
        }
      )
    %>
  </div>

  <div class="col-md-6">
    <h3>
      <%= @app.title %>
      <% unless @app.version.nil? %>
        <small>version: <%= @app.version %></small>
      <% end %>
    </h3>
    <div class="ood-appkit markdown">
      <%= OodAppkit.markdown.render(@app.description).html_safe %>

      <%- if @session_context -%>
        <%= render "form" %>
        <p>
          <%= t('dashboard.batch_connect_form_session_data_html',
                title: @app.title,
                data_link_tag: link_to(
                  t('dashboard.batch_connect_form_data_root'),
                  OodAppkit.files.url(
                    path: BatchConnect::Session.dataroot(@app.token)
                  ).to_s,
                  target: "_blank")
                )
          %>
        </p>
      <%- end -%>
    </div>
  </div><!-- /.col-md-6 -->
</div><!-- /.row -->